spring:
  application:
    name: payflow-api

  datasource:
    url: jdbc:postgresql://localhost:5433/payflow
    username: postgres
    password: payflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true