spring:
  application:
    name: payflow-api

  datasource:
    url: jdbc:postgresql://localhost:5433/payflow
    username: postgres
    password: payflow
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    sql-migration-prefix: v
    baseline-on-migrate: true